version: '3.7'
services:
    java-srv:
        build: java-srv
        ports:
        - '9000'
        labels:
        - traefik.enable=true
        - traefik.http.routers.myapp.tls=true
        - traefik.http.routers.myapp.rule=Host("myapi.docker.localhost")
    traefik:
        build: traefik
        container_name: traefik
        labels:
        - traefik.enable=true
        - traefik.http.routers.traefik=true
        ports:
        - 443:443
        - 8080:8080
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
